# Generated by Django 6.0.3 on 2026-04-16 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        ('projectapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availability',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='barbers.barberprofile'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barber_appointment_notification', to='projectapp.appointment'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barber_notifications', to='barbers.barberprofile'),
        ),
        migrations.AddField(
            model_name='unavailabledate',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbers.barberprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('barber', 'day_of_week')},
        ),
    ]
