# Generated by Django 6.0.3 on 2026-04-16 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotifications',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointment_notification', to='projectapp.appointment'),
        ),
    ]
