# Generated by Django 6.0.3 on 2026-04-23 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='stripe_payment_intent',
        ),
        migrations.AlterField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_payments', to='projectapp.appointment'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('cash', 'cash')], max_length=120),
        ),
    ]
